[package]
name = "queenx"
version = "0.1.0"
edition = "2021"

[lib]
name = "queenx"
crate-type = ["staticlib"]

[profile.dev]
panic = "abort"
lto = false

[profile.release]
panic = "abort"
lto = true
opt-level = "z"

[dependencies]
spin = "0.9"
bitflags = "2.4"

[build-dependencies]

[features]
default = []
e1000-verbose = []
kernel_test = []
fault_injection = []
# lwIP 可选协议栈特性
ipv6 = []
dhcp = []
http_client = []
mdns = []
mqtt = []
sntp = []
smtp = []
tftp = []
snmp = []
netbios = []
lwiperf = []
# 子系统可选特性
net = []
alloc = []
async = []
lock_stats = []
debug_mutex = []
atomic_stats = []
smp = []
log = []
json_export = []
