[package]
name = "queenx"
version = "0.1.0"
edition = "2021"

[lib]
name = "queenx"
crate-type = ["staticlib"]

[profile.dev]
panic = "abort"
lto = false

[profile.release]
panic = "abort"
lto = true
opt-level = "z"

[dependencies]
spin = "0.9"
bitflags = "2.4"

[build-dependencies]

[features]
default = []
e1000-verbose = []
kernel_test = []
fault_injection = []
