[package]
name = "antx-user"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "init"
path = "src/bin/init.rs"

[[bin]]
name = "shell"
path = "src/bin/shell.rs"

[[bin]]
name = "install"
path = "src/bin/install.rs"

[lib]
name = "userlib"
path = "src/lib.rs"

[profile.release]
panic = "abort"
lto = true
opt-level = "s"

[profile.dev]
panic = "abort"
